version: '3.8'

services:
  
  useraddress-api-server:
    build:
      context: ./useraddress-api
      dockerfile: Dockerfile
    image: useraddress-api-server
    container_name: simple-server-useraddress-api-container
    # command: /usr/src/app/node_modules/.bin/nodemon index.js
    volumes:
      - ./useraddress-api/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8446:8446"
    depends_on:
      - mongo-db
    # env_file: ./server/.env
    # environment:
    #   - NODE_ENV=development
    networks:
      - simple-server-network
  
  userdetails-api-server:
    build:
      context: ./userdetails-api
      dockerfile: Dockerfile
    image: userdetails-api-server
    container_name: simple-server-userdetails-api-container
    # command: /usr/src/app/node_modules/.bin/nodemon index.js
    volumes:
      - ./userdetails-api/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8447:8447"
    depends_on:
      - mongo-db
    # env_file: ./server/.env
    # environment:
    #   - NODE_ENV=development
    networks:
      - simple-server-network
  
  useredu-api-server:
    build:
      context: ./useredu-api
      dockerfile: Dockerfile
    image: useredu-api-server
    container_name: simple-server-useredu-api-container
    # command: /usr/src/app/node_modules/.bin/nodemon index.js
    volumes:
      - ./useredu-api/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8445:8445"
    depends_on:
      - mongo-db
    # env_file: ./server/.env
    # environment:
    #   - NODE_ENV=development
    networks:
      - simple-server-network
  
  userjob-api-server:
    build:
      context: ./userjob-api
      dockerfile: Dockerfile
    image: userjob-api-server
    container_name: simple-server-userjob-api-container
    # command: /usr/src/app/node_modules/.bin/nodemon index.js
    volumes:
      - ./userjob-api/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8444:8444"
    depends_on:
      - mongo-db
    # env_file: ./server/.env
    # environment:
    #   - NODE_ENV=development
    networks:
      - simple-server-network
  
  mongo-db:
    image: mongo:latest
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - simple-server-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: simple-server-frontend
    container_name: simple-server-frontend-container
    # command: npm start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - useraddress-api-server
      - userdetails-api-server
      - useredu-api-server
      - userjob-api-server
    ports:
      - "3000:3000"
    networks:
      - simple-server-network

networks:
  simple-server-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
